version: '3.3'
services:

  db:
    image: postgres:13.10-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

        #  cache:
    #    image: redis:7.0.4
      #    restart: always
      #    volumes:
      #      – ./data/cache/:/data/

  backend:
    image: geroy4ik/photo_market_backend_dev:latest
    restart: always
    volumes:
      - static_value:/app/static/
#      - static_value:/backend_static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
        #      - cache
    env_file:
      - ./.env

  frontend:
    image: geroy4ik/photo_market_frontend_dev:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      #      - ../frontend/:/app/result_build/
      - frontend:/app/build
      - static_value:/app/build/static/
#      - static_value:/frontend_static

  nginx:

    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/nginx/ssl
      - ./data/certbot/www:/var/www/certbot
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ../frontend_static/build/static/:/var/html/static/
      - frontend:/usr/share/nginx/html/
      - static_value:/var/html/static/
#      - static_value:/staticfiles/
      - media_value:/var/html/media/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - backend

volumes:
  frontend:
  static_value:
  media_value:
  pg_data:
