version: '3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: 4aiz/photo_market_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media

  gateway:
    image: 4aiz/photo_market_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media
    ports:
      - 8000:80
