version: '3.3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
#    build: ./backend/
    image: geroy4ik/photo_market_backend_dev:latest
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/media

  frontend:
#    build: ./frontend/
    image: geroy4ik/photo_market_frontend_dev:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
        - static:/frontend_static

  nginx:
#    build: ./nginx/
    image: geroy4ik/photo_market_nginx_dev:latest
    env_file: .env
    volumes:
#      - ./nginx_test.conf:/etc/nginx/conf.d/default.conf
#      - /etc/letsencrypt:/etc/letsencrypt
#      - ./data/certbot/conf:/etc/nginx/ssl
#      - ./data/certbot/www:/var/www/certbot
      - static:/staticfiles/
      - media:/media
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - 8000:80
#      - 443:443
#      - 80:80

#  certbot:
#    image: certbot/certbot:latest
#    volumes:
#      - ./data/certbot/conf:/etc/letsencrypt
#      - ./data/certbot/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

