version: '3.3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
#    image: geroy4ik/photo_market_backend_dev:latest
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/media

  frontend:
    build: ./frontend/
#    image: geroy4ik/photo_market_frontend_dev:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
        - static:/frontend_static

  nginx:
    build: ./nginx/
#    image: geroy4ik/photo_market_nginx_dev:latest
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media
    ports:
      - 8000:80
