name: Test deployer

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Copy docker-compose.yml via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.DEPLOYER_USERNAME }}
          key: ${{ secrets.DEPLOYER_SSH_ED }}
          passphrase: ${{ secrets.DEPLOYER_PASSPHRASE }}
          source: "docker-compose.production.yml"
          target: "photo_market"
