name: Front Updater

on:
  schedule:
    - cron: '00 0,14 * * *'
  workflow_dispatch:

defaults:
  run:
    working-directory: .

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout submodules
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.DISPATCH_HOOK_TOKEN }}
          submodules: true

      - name: Update submodules content
        run: git submodule update --init --recursive --checkout --remote
      - name: Update submodules index
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Frontend

  build_frontend_and_push_to_dockerhub:
    name: Build and push frontend images to DokerHub
    runs-on: ubuntu-latest
    needs: update_submodules
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME2 }}
          password: ${{ secrets.DOCKER_PASSWORD2 }}
      - name: Frontend Build and Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME2 }}/photo_boking_frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build_frontend_and_push_to_dockerhub
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Copy docker-compose.yml via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST2 }}
          username: ${{ secrets.USER2 }}
          key: ${{ secrets.SSH_KEY2 }}
          passphrase: ${{ secrets.SSH_PASSPHRASE2 }}
          source: "docker-compose.yml"
          target: "/root/photo_market"
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST2 }}
          username: ${{ secrets.USER2 }}
          key: ${{ secrets.SSH_KEY2 }}
          passphrase: ${{ secrets.SSH_PASSPHRASE2 }}
          script: |
            cd /root/photo_market
            sudo docker-compose pull frontend
            sudo docker-compose down
            sudo docker volume rm photo_market_frontend
            sudo docker-compose up -d
      - name: Executing remote ssh commands for update deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST2 }}
          username: ${{ secrets.USER2 }}
          key: ${{ secrets.SSH_KEY2 }}
          passphrase: ${{ secrets.SSH_PASSPHRASE2 }}
          script: |
            cd /root/photo_market
            sudo docker exec -it photo_market_nginx_1 bash
            cd var/html/static
            rm -r -f media/
            rm -r -f js/
            rm -r -f css/
            cd ~
            cd /
            cp -r usr/share/nginx/html/static/* var/html/static
